spring:

  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: Bank

  #settings of postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

security:
  jwt:
    secret_key: f18f88617d11108790f59d2b97e5b570b8a4d80a27416906cea81b50330cb274
    access_token_expiration: 36000000 # 10 hours
    refresh_token_expiration: 252000000 # 7 days







